[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0",
    "numpy>=1.20", # ← add numpy here
    "scipy>=1.5"       # ← and scipy if you ever import it
]
build-backend = "setuptools.build_meta"
